### ISSUE TITLE
Documenting Hack Club's Open Source Projects [Meta]

### ISSUE THREAD

**Issue by anirudhb** [hackclub/hackclub#1692]
Tracking issue for Hack Club docs (across all repositories.)

Repositories that need CONTRIBUTING.md:
- [ ] [hackclub/hackathons](https://github.com/hackclub/hackathons)
- [x] [hackclub/v3](https://github.com/hackclub/v3)
- [x] [hackclub/design-system](https://github.com/hackclub/design-system)
- [x] [hackclub/workshops](https://github.com/hackclub/workshops)
- [ ] [hackclub/cow](https://github.com/hackclub/cow) (README too)
- [x] [hackclub/summer-scrapbook](https://github.com/hackclub/summer-scrapbook)
- [ ] [hackclub/theme-starter](https://github.com/hackclub/theme-starter)
- [x] ~~[hackclub/webring](https://github.com/hackclub/webring)~~ hackclub/webring#48
- [ ] [hackclub/census](https://github.com/hackclub/census) (when PR is merged)
- [ ] [hackclub/airbridge](https://github.com/hackclub/airbridge)
- [ ] [hackclub/hack.af](https://github.com/hackclub/hack.af)
- [ ] [hackclub/clippy](https://github.com/hackclub/clippy)
- [ ] [hackclub/lore](https://github.com/hackclub/lore)
- [ ] [hackclub/awesome_hackclub_auto](https://github.com/hackclub/awesome_hackclub_auto)
- [ ] [hackclub/slack-invite-service](https://github.com/hackclub/slack-invite-service)
- [ ] [hackclub/badger](https://github.com/hackclub/badger)
- [ ] [hackclub/apply](https://github.com/hackclub/apply)
- [ ] [hackclub/banker-bot](https://github.com/hackclub/banker-bot)
- [ ] [hackclub/som-mail-system](https://github.com/hackclub/som-mail-system)
- [ ] [hackclub/scrappy](https://github.com/hackclub/scrappy)
- [ ] [hackclub/HCCore](https://github.com/hackclub/HCCore)
- [ ] [hackclub/coastguard](https://github.com/hackclub/coastguard)
- [ ] [hackclub/meet](https://github.com/hackclub/meet)
- [ ] [hackclub/banner](https://github.com/hackclub/banner)
- [ ] [hackclub/markdown](https://github.com/hackclub/markdown)
- [ ] [hackclub/events](https://github.com/hackclub/events)
- [ ] [hackclub/jobs](https://github.com/hackclub/jobs)
- [ ] [hackclub/scrapbook-network](https://github.com/hackclub/scrapbook-network)
- [ ] [hackclub/chess-bot](https://github.com/hackclub/chess-bot)
- [ ] [hackclub/hackclub.es](https://github.com/hackclub/hackclub.es) (ARCHIVE)
- [ ] [hackclub/Rudolph](https://github.com/hackclub/Rudolph)
- [ ] [hackclub/leap-site](https://github.com/hackclub/leap-site)
- [ ] [hackclub/airbender](https://github.com/hackclub/airbender)
- [ ] [hackclub/assets](https://github.com/hackclub/assets)
- [ ] [hackclub/slash-z](https://github.com/hackclub/slash-z)
- [ ] [hackclub/the-fuzz](https://github.com/hackclub/the-fuzz)
- [ ] [hackclub/map](https://github.com/hackclub/map)
- [ ] [hackclub/season](https://github.com/hackclub/season)
- [ ] [hackclub/hack-coins](https://github.com/hackclub/hack-coins) (archive?)
- [ ] [hackclub/oxygen-mask](https://github.com/hackclub/oxygen-mask)
- [ ] [hackclub/streambot](https://github.com/hackclub/streambot)
- [x] [meta] update [hackclub/hackclub](https://github.com/hackclub/hackclub) CONTRIBUTING.md template to use GIFs that reflect new GitHub interface hackclub/hackclub#1703

Make a comment on this GitHub issue if you've completed any of these and I'll mark it off!

**Comment by eilla1** [comment]
I completed the CONTRIBUTING.md for hackclub/webring!

**Comment by sampoder** [comment]
Some of these are no longer maintained, is it alright if I trim the list?

**Comment by sampoder** [comment]
Also, DS has contributing docs already so marking that off

**Comment by anirudhb** [comment]
@sampoder even though DS has contributing docs already it doesn't have a toplevel CONTRIBUTING.md (which could just be a link to the one in docs/). Having one at the toplevel is a normal standard for open source projects to follow.

**Comment by sampoder** [comment]
Ok, I'll fix it

**Comment by sampoder** [comment]
I think a good thing would be to create a standard set for the Next.js projects

**Comment by eilla1** [comment]
[hackclub/hackclub#1701](https://github.com/hackclub/hackclub/pull/1701) I made a pr to update the contributing GIFs to reflect the new GitHub interface.

**Comment by me-sachin** [comment]
I think a good thing would be to create a standard set for the Next.js projects

**Comment by me-sachin** [comment]
create a standard set for the Next.js projects👾

**Comment by Ash-KODES** [comment]
Can I work on this?

**Comment by me-sachin** [comment]
> 

yess
