### ISSUE TITLE
Heroku breach security tasks [Meta]

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hackclub#1767]
Context: https://status.heroku.com/incidents/2413?updated

**If you know a repo should be added, please include it to the list!** Hack Club is a big place with a lot of deployed stuff, so extra hands on this helps.

This ticket is a meta issue to track what we need to do across all our repos that were deployed to Heroku. The following is a list of repos that should have a ticket for this incident (ie, hackclub/toriel will have a ticket for rotating slack API credentials). Once the ticket is created and linked here, the repo can be checked off the list:

- [x] hackclub/toriel https://github.com/hackclub/toriel/issues/45
- [x] hackclub/bank https://github.com/hackclub/bank/issues/2538
   - Tangentially related: https://github.com/hackclub/bank/issues/2541
- [x] hackclub/orpheus https://github.com/hackclub/orpheus-bot/issues/67
- [x] hackclub/clippy https://github.com/hackclub/clippy/issues/50
- [ ] hackclub/bucky (cc @zachlatta)
- [x] hackclub/api https://github.com/hackclub/api/issues/470
- [ ] hackclub/airbridge
- [x] hackclub/slash-z https://github.com/hackclub/slash-z/issues/57
- [x] hackclub/hack.af https://github.com/hackclub/hack.af/issues/28
- [ ] maxwofford/mail-dog
- [ ] hackclub/cow
- [x] hackclub/lino https://github.com/hackclub/lino/issues/5
- [x] hackclub/github-oauth https://github.com/hackclub/github-oauth/issues/13
- [ ] Hugoyhu/mailcorgiJS
- [x] hackclub/mfa https://github.com/hackclub/mfa/issues/4

**Comment by maxwofford** [comment]
There isn't a good way to link to a specific update on https://status.heroku.com/incidents/2413?updated, but they just posted their May 7, 2022 00:29 UTC update that mentions the db holding env variables was accessed, the decryption for that db wasn't accessed.
